In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# CSV file
data = pd.read_csv('data/iris.csv', header=(0))
data.head(25)

    sepal_length  sepal_width  petal_length  petal_width species
0            5.1          3.5           1.4          0.2  setosa
1            4.9          3.0           1.4          0.2  setosa
2            4.7          3.2           1.3          0.2  setosa
3            4.6          3.1           1.5          0.2  setosa
4            5.0          3.6           1.4          0.2  setosa
5            5.4          3.9           1.7          0.4  setosa
6            4.6          3.4           1.4          0.3  setosa
7            5.0          3.4           1.5          0.2  setosa
8            4.4          2.9           1.4          0.2  setosa
9            4.9          3.1           1.5          0.1  setosa
10           5.4          3.7           1.5          0.2  setosa
11           4.8          3.4           1.6          0.2  setosa
12           4.8          3.0           1.4          0.1  setosa
13           4.3          3.0           1.1          0.1  setosa
14           5.8          4.0           1.2          0.2  setosa
15           5.7          4.4           1.5          0.4  setosa
16           5.4          3.9           1.3          0.4  setosa
17           5.1          3.5           1.4          0.3  setosa
18           5.7          3.8           1.7          0.3  setosa
19           5.1          3.8           1.5          0.3  setosa
20           5.4          3.4           1.7          0.2  setosa
21           5.1          3.7           1.5          0.4  setosa
22           4.6          3.6           1.0          0.2  setosa
23           5.1          3.3           1.7          0.5  setosa
24           4.8          3.4           1.9          0.2  setosa

## Normalização:

In [5]:
from hashlib import new
from sklearn.preprocessing import MinMaxScaler
# considera somente os atributos, ignorando a última coluna, que contem a classe
X = np.array(data[data.columns[0:data.shape[1]-1]])
# prepara a função para transformar os dados
scaler = MinMaxScaler(feature_range=(0, 1))
# Realiza a normalização e coloca em um novo vetor
X_norm = scaler.fit_transform(X)
new_data = pd.DataFrame(X_norm)
new_data.rename(columns = {0: 'sepal_length', 1:'sepal_width', 2: 'petal_length', 3: 'petal_width'}, inplace = True)
new_data.head(25)

    sepal_length  sepal_width  petal_length  petal_width
0       0.222222     0.625000      0.067797     0.041667
1       0.166667     0.416667      0.067797     0.041667
2       0.111111     0.500000      0.050847     0.041667
3       0.083333     0.458333      0.084746     0.041667
4       0.194444     0.666667      0.067797     0.041667
5       0.305556     0.791667      0.118644     0.125000
6       0.083333     0.583333      0.067797     0.083333
7       0.194444     0.583333      0.084746     0.041667
8       0.027778     0.375000      0.067797     0.041667
9       0.166667     0.458333      0.084746     0.000000
10      0.305556     0.708333      0.084746     0.041667
11      0.138889     0.583333      0.101695     0.041667
12      0.138889     0.416667      0.067797     0.000000
13      0.000000     0.416667      0.016949     0.000000
14      0.416667     0.833333      0.033898     0.041667
15      0.388889     1.000000      0.084746     0.125000
16      0.305556     0.791667      0.050847     0.125000
17      0.222222     0.625000      0.067797     0.083333
18      0.388889     0.750000      0.118644     0.083333
19      0.222222     0.750000      0.084746     0.083333
20      0.305556     0.583333      0.118644     0.041667
21      0.222222     0.708333      0.084746     0.125000
22      0.083333     0.666667      0.000000     0.041667
23      0.222222     0.541667      0.118644     0.166667
24      0.138889     0.583333      0.152542     0.041667

## Padronização

In [6]:
from sklearn.preprocessing import StandardScaler
X = np.array(data[data.columns[0:data.shape[1]-1]])
# prepara a função para transformar os dados
scaler = StandardScaler().fit(X)
# realiza a padronização (média=0, variância = 1)
rescaledX = scaler.transform(X)
new_data = pd.DataFrame(rescaledX)
new_data.rename(columns = {0: 'sepal_length', 1:'sepal_width', 2: 'petal_length', 3: 'petal_width'}, inplace = True)
new_data.head(25)

    sepal_length  sepal_width  petal_length  petal_width
0      -0.900681     1.032057     -1.341272    -1.312977
1      -1.143017    -0.124958     -1.341272    -1.312977
2      -1.385353     0.337848     -1.398138    -1.312977
3      -1.506521     0.106445     -1.284407    -1.312977
4      -1.021849     1.263460     -1.341272    -1.312977
5      -0.537178     1.957669     -1.170675    -1.050031
6      -1.506521     0.800654     -1.341272    -1.181504
7      -1.021849     0.800654     -1.284407    -1.312977
8      -1.748856    -0.356361     -1.341272    -1.312977
9      -1.143017     0.106445     -1.284407    -1.444450
10     -0.537178     1.494863     -1.284407    -1.312977
11     -1.264185     0.800654     -1.227541    -1.312977
12     -1.264185    -0.124958     -1.341272    -1.444450
13     -1.870024    -0.124958     -1.511870    -1.444450
14     -0.052506     2.189072     -1.455004    -1.312977
15     -0.173674     3.114684     -1.284407    -1.050031
16     -0.537178     1.957669     -1.398138    -1.050031
17     -0.900681     1.032057     -1.341272    -1.181504
18     -0.173674     1.726266     -1.170675    -1.181504
19     -0.900681     1.726266     -1.284407    -1.181504
20     -0.537178     0.800654     -1.170675    -1.312977
21     -0.900681     1.494863     -1.284407    -1.050031
22     -1.506521     1.263460     -1.568735    -1.312977
23     -0.900681     0.569251     -1.170675    -0.918558
24     -1.264185     0.800654     -1.056944    -1.312977